### ISSUE TITLE
question about diffusion model

### ISSUE THREAD

**Issue by 1184125805** [mainaksingha01/ODG-CLIP#2]
May I ask if the training and the generation of images using stable diffusion are performed simultaneously? Does the time taken for stable diffusion to generate images significantly affect the training speed?

**Comment by mainaksingha01** [comment]
Yes the new images are generated during training. It takes around 3 seconds to generate an image, so it affects the training speed a bit, but not so much. However, the generation part is excluded during inference, so the inference speed is fine.

**Comment by 1184125805** [comment]
thank you very much. I want to add frozen diffusion models into object detection tasks，is that possible to add one generated image every iteration?

**Comment by mainaksingha01** [comment]
It is possible I guess
